### ISSUE TITLE
Convert code to MCV structure(M)

### ISSUE THREAD

**Issue by Qpirons** [mucs420f19/Hercules#91]
Create a controller file

**Comment by Qpirons** [comment]
Primary Quinn

**Comment by silviuburz** [comment]
Spent 4 hours on Nov 9, implemented full controller/model functionality and adjusted the REPL to suit this. I left comments in the Gui.h explaining what needs to be modified for the controller access.

Spent 1 hour on Nov 10 adjusting tests to reflect this.

Model and Controller part is done, and the REPL reflects this.

The GUI still needs to be modified to adhere to this and behavior like a true view. This includes creating functions that declare GUI items instead of explicitly declaring them.

**Comment by lawilli4** [comment]
This task was decomposed into two overarching tasks - the REPL refactor and the GUI refactor.
